name: Run Doctor Availability Check

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      URL: ${{ secrets.URL }}
      DOCTOR: ${{ secrets.DOCTOR }}
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules and npm
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
          ${{ runner.os }}-modules-

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-browsers

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright + system deps
        run: npx playwright install --with-deps

      - name: Add credentials.json
        run: |
          echo "${GOOGLE_CREDENTIALS}" > src/credentials.json

      - name: Run script directly
        run: npx ts-node tests/verify-doctor-availibility.spec.ts