name: Run Doctor Availability Check

on:
  schedule:
    # Uruchamiaj co 10 minut
    - cron: "*/10 4-22 * * *"
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest

    env: # <------ USTAW TUTAJ ENV, żeby były dostępne we wszystkich krokach!
      URL: ${{ secrets.URL }}
      DOCTOR: ${{ secrets.DOCTOR }}
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      TWILIO_SID: ${{ secrets.TWILIO_SID }}
      TWILIO_AUTH: ${{ secrets.TWILIO_AUTH }}
      TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
      SMS_RECIPIENTS: ${{ secrets.SMS_RECIPIENTS }}
      SMSAPI_TOKEN: ${{ secrets.SMSAPI_TOKEN}}
      SMSAPI_FROM: ${{ secrets.SMSAPI_FROM}}
      SMSAPI_TO: ${{ secrets.SMSAPI_TO}}
    steps:
      # 1. Checkout repozytorium
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Ustaw Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalacja zależności
      - name: Install dependencies
        run: npm install

      - name: Install Chromium only
        run: npx playwright install chromium

      # 4. Ustaw zmienne środowiskowe
      - name: Set environment variables
        env:
          URL: ${{ secrets.URL }}
          DOCTOR: ${{ secrets.DOCTOR }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: echo "Environment variables set"

      # 5. Dodaj plik credentials.json
      - name: Add credentials.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "${GOOGLE_CREDENTIALS}" > src/credentials.json

      # 6. Uruchom skrypt
      - name: Run script
        run: npx playwright test tests/verify-doctor-availibility.spec.ts
      # 7. Uruchom monitor A1 i wyślij SMS jeśli trzeba
      - name: Run A1 monitor and notify
        run: npx ts-node src/checkAndNotify.ts
